site_name: YaCy
site_author: Michael Christen
site_description: "YaCy P2P - Decentralized Search Engine"
site_url: "https://yacy.net"
repo_url: "https://github.com/yacy/yacy_net_homepage.git"

theme:
    name: null
    custom_dir: 'cinder-superhero'

nav:
  - Home: index.md
  - Demo: demonstration_tutorial_screenshot.md
  - Download: download_installation.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
